spring:
 profiles:
    active: dev
server:
 port: 20000
---
spring:
 profiles: dev
 data:
  mongodb:
   database: sitesurvey
   host: ds017514.mlab.com
   port: 17514
   username: rajiv
   password: rajivkr
---
spring:
 profiles: dev-cloud
 data:
  mongodb:
   database: sitesurvey
   host: ds017514.mlab.com
   port: 17514
   username: rajiv
   password: rajivkr